### ISSUE TITLE
[twitchpress_connect_button] doesn't work

### ISSUE THREAD

**Issue by pauloedspinho20** [RyanBayne/TwitchPress-Login-Extension#31] opened 2019-01-21 18:30 UTC
I've installed all extensions to integrate a Twitch login/registration button and placed the [twitchpress_connect_button]  on my Ultimate Member pages.

- TwitchPress Login Extension
- TwitchPress Sync Extension
- TwitchPress Login Extension
- TwitchPress UM Extension

Despite this, the shortcode doesn't work and a string is printed on pages.
I'm missing something?

**Comment by RyanBayne** [comment] 2019-01-21 18:40
I'm going to assume you haven't activated Twitch API 6 - Helix

I recommended waiting until Helix is fully supported before moving ahead with this plugin. Just to ensure it meets your requirements in the time-frame you expect. 

* Any reason the login extension shows twice? 
* Sync extension is no longer required but it has been kept temporarily for those using old versions. 
* UM extension is not required for the connect button. 

The cause of the problem will be something simple because it can work. I'll take a look for anything obvious.

**Comment by RyanBayne** [comment] 2019-02-04 00:42
My test has allowed me to display the Twitch login button (while logged out) on a page. The button is hidden on that page when I'm logged into WP. 

The log shows enough success to indicate a smooth login - however there was one error...

`[04-Feb-2019 00:36:36 UTC] PHP Notice:  Undefined variable: state_code in D:\xampp\htdocs\TwitchPress\branches\beta\wp-content\plugins\twitchpress-login-extension\class.twitchpress-login-kraken.php on line 834
[`

Despite this I was sent to WP admin. I will look into the state_code issue and that is all. There is not enough information or evidence to look into any other issue including "a string is printed on pages" so I'll close this issue.

**Closed by RyanBayne** 2019-02-04 00:42 UTC
Labels: bug
